DROP TABLE IF EXISTS payment_transaction;
DROP TABLE IF EXISTS payment_card;
DROP TABLE IF EXISTS bank;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS client;
DROP TABLE IF EXISTS client_address;
DROP TABLE IF EXISTS city;